title: <a href="https://github.com/defitalutfiah/defitalutfiah.github.io/">defita</a> # your name (or website title) here
logo: "/main/images/456.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An undergraduate student from department of Economics Universitas Padjadjaran who interested to data analytics and social issues  
  <br><br>
  <a href="https://www.instagram.com/defitaalutfiah/">Instagram</a>  
  <br><br>
  <a href="https://www.linkedin.com/in/defitalutfiah/">View My LinkedIn Profile</a> 
  
  
  
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
